### ISSUE TITLE
Can't import opendatasets on Colab

### ISSUE THREAD

**Issue by mvortizr** [JovianML/opendatasets#2]
Trying to import the library on Colab gives this error:

```

AttributeError: module 'urllib' has no attribute 'urlopen'
```

**Comment by mvortizr** [comment]
I'm using 
```
!pip install opendatasets --upgrade
```
and 
```
import opendatasets as od
```

**Comment by ameyalaad** [comment]
Hi, I can confirm this issue occurs with me as well on Google Colab. It seems for python 3 and above, you have to individually import the urllib.requests, and urllib.error module. 

The script creating the issue is opendatasets/utils/network.py, where adding the line:
```py
import urllib.request
```
solves the issue.

@aakashns can I take this up?

**Comment by VedantMadane** [comment]
You may have to 
`! pip install requests`
first.

**Comment by aakashns** [comment]
Thanks for reporting! This issue has been fixed in https://github.com/JovianML/opendatasets/commit/662056c04b7612f75ca46148c5fefdbea168aa9f
